// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYOwRvnJYEHYOClAprZPI9BdvRrm_BkTI',
    appId: '1:206870869909:web:fe3d4013440b89e23da89c',
    messagingSenderId: '206870869909',
    projectId: 'e-magang-4187c',
    authDomain: 'e-magang-4187c.firebaseapp.com',
    storageBucket: 'e-magang-4187c.firebasestorage.app',
    measurementId: 'G-XG0JMKZSCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuYnFXvF7j9sd_4XlxTeYjUyVXJSJ09F8',
    appId: '1:206870869909:android:a1c353d24fe70ca73da89c',
    messagingSenderId: '206870869909',
    projectId: 'e-magang-4187c',
    storageBucket: 'e-magang-4187c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2tU6vH8r-1tXr-nOZ99TKfFKWEUkDbLI',
    appId: '1:206870869909:ios:e6bba45d36b9a6af3da89c',
    messagingSenderId: '206870869909',
    projectId: 'e-magang-4187c',
    storageBucket: 'e-magang-4187c.firebasestorage.app',
    iosBundleId: 'com.example.sistemBimbinganMagang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2tU6vH8r-1tXr-nOZ99TKfFKWEUkDbLI',
    appId: '1:206870869909:ios:e6bba45d36b9a6af3da89c',
    messagingSenderId: '206870869909',
    projectId: 'e-magang-4187c',
    storageBucket: 'e-magang-4187c.firebasestorage.app',
    iosBundleId: 'com.example.sistemBimbinganMagang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYOwRvnJYEHYOClAprZPI9BdvRrm_BkTI',
    appId: '1:206870869909:web:eec608d2aff044803da89c',
    messagingSenderId: '206870869909',
    projectId: 'e-magang-4187c',
    authDomain: 'e-magang-4187c.firebaseapp.com',
    storageBucket: 'e-magang-4187c.firebasestorage.app',
    measurementId: 'G-DFTEZDNKMC',
  );
}
